name: bacterial-genomics-tutorial
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - sickle
  - fastqc
  - python=3
  - minimap2
  - ragtag
  - abricate
  - mlst
  - prokka
  - quast
  - trimmomatic
  - pip
  - pip:
      - numpy
      - matplotlib
      - matplotlib-venn
      - biopython
      - dREP
      - minimap2
      - mafft
      - perl-db-file
      - perl-padwalker
      - porechop
      - mash
      - roary
      - spades
      - samtools
      - bwa
      - sra-tools
      - sickle-trim
      - mummer
